clang hello.c \
	-target x86_64-unknown-windows \
	-std=c17 \
	-Wall \
	-Wextra \
	-Wpedantic \
	-mno-red-zone \
	-ffreestanding \
	-I/home/rdraper/gnu-efi/inc/ \
	-I $HOME/gnu-efi/inc/x86_64 \
	-nostdlib \
	-fuse-ld=lld-link-18 \
	-Wl,-subsystem:efi_application \
	-Wl,-entry:efi_main \
	-o BOOTX64.EFI
